// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfvoodknaiolgigupqzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdm9vZGtuYWlvbGdpZ3VwcXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzUyNTksImV4cCI6MjA2NTY1MTI1OX0.PHvne7AI-ufhQ1wD3xierox32bXan2xi5nRZx9f95-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);